### PR TITLE
UI Update for Login Screen for Issue#9

### PR DESCRIPTION
**Pull request by error404-beep**
UI Update regarding #9 
Following are the changes:
- Added assets and fonts used on the Login screen.
- Updated the design according to the XD design provided. ( https://xd.adobe.com/view/3884d012-2dd1-4f15-bfa3-e80f6e45e473-6dd7/screen/5d7b2b92-ee86-4d67-a235-ae1b3ba0fa57/ ).
- Added logic to make sure no overflow in landscape mode.

### CODE REVIEW

**Comment by PrarabdhGarg** [comment]
@error404-beep could you add a screenshot to the PR description of the updated layout.

**Comment by error404-beep** [comment]
Screenshot_1596366563
Screenshot_1596366567
Here are some screenshot.
I have noticed that the Radar heading is aligned left in landscape mode. I will update this PR after this fix.
But when I enclose the `Column` in `SafeArea` , there is overflow of 1.6px. I m currently working to solve this overlook.
Here are some screenshot after the changes I suggested:
Screenshot_1596366741
Screenshot_1596366747

**Comment by error404-beep** [comment]
I was able to fix the eariler issue with `Expanded`. Will update the PR now.
Screenshot_1596367752
Screenshot_1596367755

**Comment by PrarabdhGarg** [comment]
@error404-beep Great Work. Keep up the spirit.

**Pull request merged**
